# Dependabot 🤖

version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "mod"
      include: "scope"
    reviewers:
      - "swand0g"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions"
      include: "scope"
    reviewers:
      - "swand0g"
