name: Go All

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [arm, arm64, amd64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set name
        run: |
          if [ "${{ matrix.arch }}" == "amd64" ]; then
            echo "BIN_NAME=autocomm-linux" >> $GITHUB_ENV
          elif [ "${{ matrix.arch }}" == "arm" ]; then
            echo "BIN_NAME=autocomm-arm32" >> $GITHUB_ENV
          else
            echo "BIN_NAME=autocomm-${{ matrix.arch }}" >> $GITHUB_ENV
          fi

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o ./bin/${{ env.BIN_NAME }} ./...

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}
          path: ./bin/${{ env.BIN_NAME }}
  
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v -o ./bin/ ./...

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: autocomm-macos
          path: ./bin/autocomm
  
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v -o ./bin/ ./...

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: autocomm-windows
          path: ./bin/autocomm.exe
