name: Go All

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v -o ./bin/ ./...

    - name: Archive binaries
      uses: actions/upload-artifact@v3
      with:
        name: autocomm-macos
        path: ./bin/autocomm

    - name: Test
      run: go test -v ./...
